services:
  telegram:
    image: lscr.io/linuxserver/telegram:latest
    container_name: stacktek-telegram
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/core/.podman/stacktek/data/telegram:/config
    expose:
      - "3000"
      - "3001"
    shm_size: "1gb"
    restart: unless-stopped
