FROM docker.io/library/caddy:2-builder AS builder

RUN xcaddy build \
    --with github.com/corazawaf/coraza-caddy/v2 \
    --with github.com/corazawaf/coraza-coreruleset

FROM docker.io/library/caddy:2

LABEL org.opencontainers.image.title="Caddy + Coraza" \
      org.opencontainers.image.licenses="Apache-2.0"

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

EXPOSE 443
