services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
    environment:
      GLOBAL_LOG_LEVEL: INFO
      WEBUI_SECRET_KEY: ${WEBUI_SECRET_KEY:-}
      WEBUI_NAME: StackTek
    volumes:
      - $HOME/.openwebui:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    expose:
      - "8080"
    ports:
      - "8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
