services:
  chromium:
    image: lscr.io/linuxserver/chromium:latest
    container_name: stacktek-chromium
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/core/.podman/stacktek/data/chromium:/config
    expose:
      - "3000"
      - "3001"
    shm_size: "1gb"
    restart: unless-stopped