FROM node:22-bookworm-slim AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install --omit=dev

COPY . .

FROM node:22-alpine

RUN apk add --no-cache tini

WORKDIR /app

COPY --from=builder /app /app

EXPOSE 3000

ENV HOST=0.0.0.0
ENV PORT=3000

ENTRYPOINT ["/sbin/tini", "--"]
CMD ["node", "space", "serve"]
