services:
  macos:
    image: ghcr.io/dockur/macos:latest
    container_name: macos
    environment:
      VERSION: "15"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    expose:
      - "8006"
      - "5900/tcp"
      - "5900/udp"
    volumes:
      - ./macos:/storage
    restart: always
    stop_grace_period: 2m