services:
  signal:
    image: lscr.io/linuxserver/signal:latest
    container_name: stacktek-signal
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - $HOME/stacktek/data/signal:/config
    expose:
      - "3000"
      - "3001"
    shm_size: "1gb"
    restart: unless-stopped
